version: '3'

services:
  remote_auth:
    container_name: remote_auth
    build: ./open_auth
    volumes:
      - oauth_volume:/django
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8000" #host port changed to 8080
    networks:
      - nw
    depends_on:
      - postgreDB
    restart: on-failure  # Ensures container restarts if it fails
    env_file:
      - .env  # Add this line
    
  postgreDB:
    image: postgres:16
    container_name: postgreDB
    environment:
      POSTGRES_DB: users_42
      POSTGRES_USER: ayylaaba
      POSTGRES_PASSWORD: password
    volumes:
      - /home/ayoub/data/db:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - nw
  nginx:
    build: ./nginx  # Ensure this points to your Nginx directory with the Dockerfile and nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - remote_auth
    volumes:
      - front_volume:/var/www/front  # Front-end files volume
    networks:
      - nw
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - nw
  xo_game:
    build: ./Xo_Game/xo_game/
    ports:
      - 8001:8001
    depends_on:
      - postgreDB
    networks:
      - nw
  chatapp:
    container_name: chatapp
    build: ./chatapp
    ports:
      - 8003:8003
    environment:
      - DATABASE_HOST=chat_db
      - DATABASE_PORT=5433
      - DATABASE_NAME=chat
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD='123'
    depends_on:
      - chat_db
    env_file:
      - ./chatapp/.env
    networks:
      - nw
  chat_db:
    image: postgres:latest
    container_name: chat_db
    restart: on-failure:5
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - database-postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - nw
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "hicham@example.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "5050:80"
    networks:
      - nw
  pingpong:
    build: ./PingPong/pinpong/pinpong/
    ports:
      - 8002:8002
    depends_on:
      - postgreDB
    networks:
      - nw
volumes:
  database-postgres:
  postgre_volume:
  front_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nginx/srcs
  oauth_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./open_auth
networks:
  nw:
    driver: bridge